
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: johnny
      POSTGRES_PASSWORD: 080906
      POSTGRES_DB: insurance
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: insurance-backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: johnny
      DB_PASSWORD: 080906
      DB_NAME: insurance
    ports:
      - "8080:8080"
    command: ./app  # если ты собрал в app, можно заменить


volumes:
  pgdata: